[package]
name = "fail"
version = "0.1.1"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["failpoints", "fail"]
repository = "https://github.com/pingcap/fail-rs"
readme = "README.md"
homepage = "https://github.com/pingcap/fail-rs"
documentation = "https://docs.rs/fail"
description = "Failpoints for rust."
categories = ["development-tools::testing"]

[dependencies]
log = "0.3"
lazy_static = "0.2"
rand = "0.3"
